services:
  db:
    image: postgres:15
    container_name: local_points_system_postgres
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - 5432:5432
    networks:
      - onyx_network

networks:
  onyx_network:
    driver: bridge
