"""Add PointsPointType table

Revision ID: 0580221c6f58
Revises: 1b9300fdfc11
Create Date: 2025-08-21 09:23:05.552781

"""
import sqlmodel
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0580221c6f58'
down_revision: Union[str, None] = '1b9300fdfc11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('points_point_types',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('partner_slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_points_point_types_partner_slug'), 'points_point_types', ['partner_slug'], unique=False)
    op.create_index(op.f('ix_points_point_types_slug'), 'points_point_types', ['slug'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_points_point_types_slug'), table_name='points_point_types')
    op.drop_index(op.f('ix_points_point_types_partner_slug'), table_name='points_point_types')
    op.drop_table('points_point_types')
    # ### end Alembic commands ###
