"""Create PointsPartnerSnapshot table

Revision ID: 0f2d9f9d058c
Revises: 8e572260fec0
Create Date: 2025-08-22 09:08:15.417559

"""
import sqlmodel
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f2d9f9d058c'
down_revision: Union[str, None] = '8e572260fec0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('points_partner_snapshots',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('vault_address', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('partner_slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('points_total', sa.Numeric(precision=36, scale=18), nullable=False),
    sa.Column('snapshot_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vault_address', 'partner_slug', 'snapshot_at', name='uq_vault_partner_snapshot_time')
    )
    op.create_index(op.f('ix_points_partner_snapshots_partner_slug'), 'points_partner_snapshots', ['partner_slug'], unique=False)
    op.create_index(op.f('ix_points_partner_snapshots_snapshot_at'), 'points_partner_snapshots', ['snapshot_at'], unique=False)
    op.create_index(op.f('ix_points_partner_snapshots_vault_address'), 'points_partner_snapshots', ['vault_address'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_points_partner_snapshots_vault_address'), table_name='points_partner_snapshots')
    op.drop_index(op.f('ix_points_partner_snapshots_snapshot_at'), table_name='points_partner_snapshots')
    op.drop_index(op.f('ix_points_partner_snapshots_partner_slug'), table_name='points_partner_snapshots')
    op.drop_table('points_partner_snapshots')
    # ### end Alembic commands ###
