"""Create PointsUserPointHistory table

Revision ID: 3638a3631287
Revises: 59f4d9193846
Create Date: 2025-08-21 10:52:21.380414

"""
import sqlmodel
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '3638a3631287'
down_revision: Union[str, None] = '59f4d9193846'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('points_user_point_history',
    sa.Column('id', postgresql.UUID(as_uuid=True), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('source_event_id', sa.Uuid(), nullable=False),
    sa.Column('wallet_address', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('campaign_id', sa.Uuid(), nullable=False),
    sa.Column('point_type_slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('points_change', sa.Numeric(precision=36, scale=18), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['points_campaign.id'], ),
    sa.ForeignKeyConstraint(['point_type_slug'], ['points_point_types.slug'], ),
    # sa.ForeignKeyConstraint(['source_event_id'], ['points_user_campaign_points.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_points_user_point_history_campaign_id'), 'points_user_point_history', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_points_user_point_history_point_type_slug'), 'points_user_point_history', ['point_type_slug'], unique=False)
    op.create_index(op.f('ix_points_user_point_history_source_event_id'), 'points_user_point_history', ['source_event_id'], unique=False)
    op.create_index(op.f('ix_points_user_point_history_wallet_address'), 'points_user_point_history', ['wallet_address'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_points_user_point_history_wallet_address'), table_name='points_user_point_history')
    op.drop_index(op.f('ix_points_user_point_history_source_event_id'), table_name='points_user_point_history')
    op.drop_index(op.f('ix_points_user_point_history_point_type_slug'), table_name='points_user_point_history')
    op.drop_index(op.f('ix_points_user_point_history_campaign_id'), table_name='points_user_point_history')
    op.drop_table('points_user_point_history')
    # ### end Alembic commands ###
