"""Create PartnerProtocolEvent table

Revision ID: 58fc669c131f
Revises: c49d4ee35b08
Create Date: 2025-08-23 02:35:19.218329

"""
import sqlmodel
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58fc669c131f'
down_revision: Union[str, None] = 'c49d4ee35b08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('partner_protocol_event',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tx_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('block_number', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('wallet_address', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('protocol_slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False),

    sa.Column(
        'protocol_type',
        sa.Enum('DEX_UNISWAPV3','LENDING_HYPURRFI','YIELD_PENDLE', name='protocoltype', create_type=False),
        nullable=False
    ),

    sa.Column('quantity_type', sa.Enum('LP', 'YT', 'BORROW', name='quantitytype', create_type=False), nullable=False),

    sa.Column('quantity_change', sa.Numeric(precision=78, scale=0), nullable=False),
    sa.Column('quantity_change_usd', sa.Numeric(precision=36, scale=18), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_partner_protocol_event_block_number'), 'partner_protocol_event', ['block_number'], unique=False)
    op.create_index(op.f('ix_partner_protocol_event_protocol_slug'), 'partner_protocol_event', ['protocol_slug'], unique=False)
    op.create_index(op.f('ix_partner_protocol_event_timestamp'), 'partner_protocol_event', ['timestamp'], unique=False)
    op.create_index(op.f('ix_partner_protocol_event_tx_hash'), 'partner_protocol_event', ['tx_hash'], unique=True)
    op.create_index(op.f('ix_partner_protocol_event_wallet_address'), 'partner_protocol_event', ['wallet_address'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # The downgrade should only drop the table, not the ENUM types,
    # as they are still used by the PartnerUserPosition table.
    # The original auto-generated code is correct here.
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_partner_protocol_event_wallet_address'), table_name='partner_protocol_event')
    op.drop_index(op.f('ix_partner_protocol_event_tx_hash'), table_name='partner_protocol_event')
    op.drop_index(op.f('ix_partner_protocol_event_timestamp'), table_name='partner_protocol_event')
    op.drop_index(op.f('ix_partner_protocol_event_protocol_slug'), table_name='partner_protocol_event')
    op.drop_index(op.f('ix_partner_protocol_event_block_number'), table_name='partner_protocol_event')
    op.drop_table('partner_protocol_event')
    # ### end Alembic commands ###