"""Add PointsUserPoint table

Revision ID: 71efecc1be69
Revises: 7e9071e72397
Create Date: 2025-08-21 10:49:04.637066

"""
import sqlmodel
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '71efecc1be69'
down_revision: Union[str, None] = '7e9071e72397'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('points_user_point',
    sa.Column('id', postgresql.UUID(as_uuid=True), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('wallet_address', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('point_type_slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('points', sa.Numeric(precision=36, scale=18), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['point_type_slug'], ['points_point_types.slug'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('wallet_address', 'point_type_slug', name='uq_summary_wallet_point_type')
    )
    op.create_index(op.f('ix_points_user_point_point_type_slug'), 'points_user_point', ['point_type_slug'], unique=False)
    op.create_index(op.f('ix_points_user_point_wallet_address'), 'points_user_point', ['wallet_address'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_points_user_point_wallet_address'), table_name='points_user_point')
    op.drop_index(op.f('ix_points_user_point_point_type_slug'), table_name='points_user_point')
    op.drop_table('points_user_point')
    # ### end Alembic commands ###
