"""Create VaultsUserPosition table

Revision ID: 7d766f5a3758
Revises: 29c00d872b7e
Create Date: 2025-08-25 17:35:37.778142

"""
import sqlmodel
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d766f5a3758'
down_revision: Union[str, None] = '29c00d872b7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vaults_user_position',
    sa.Column('user_address', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('vault_id', sa.Uuid(), nullable=False),
    sa.Column('total_shares', sa.Float(), nullable=False),
    sa.Column('total_assets_value', sa.Float(), nullable=False),
    sa.Column('unrealized_pnl', sa.Float(), nullable=False),
    sa.Column('realized_pnl', sa.Float(), nullable=False),
    # sa.Column('average_cost_basis', sa.Float(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['vault_id'], ['vaults.id'], ),
    sa.PrimaryKeyConstraint('user_address', 'vault_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vaults_user_position')
    # ### end Alembic commands ###
