"""Add PointsUserCampaignPoints table

Revision ID: 7e9071e72397
Revises: 0580221c6f58
Create Date: 2025-08-21 09:52:21.159720

"""
import sqlmodel
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e9071e72397'
down_revision: Union[str, None] = '0580221c6f58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('points_user_campaign_points',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('wallet_address', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('campaign_id', sa.Uuid(), nullable=False),
    sa.Column('point_type_slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('points_earned', sa.Numeric(precision=36, scale=18), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['points_campaign.id'], ),
    sa.ForeignKeyConstraint(['point_type_slug'], ['points_point_types.slug'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('wallet_address', 'campaign_id', name='uq_wallet_campaign')
    )
    op.create_index(op.f('ix_points_user_campaign_points_campaign_id'), 'points_user_campaign_points', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_points_user_campaign_points_point_type_slug'), 'points_user_campaign_points', ['point_type_slug'], unique=False)
    op.create_index(op.f('ix_points_user_campaign_points_wallet_address'), 'points_user_campaign_points', ['wallet_address'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_points_user_campaign_points_wallet_address'), table_name='points_user_campaign_points')
    op.drop_index(op.f('ix_points_user_campaign_points_point_type_slug'), table_name='points_user_campaign_points')
    op.drop_index(op.f('ix_points_user_campaign_points_campaign_id'), table_name='points_user_campaign_points')
    op.drop_table('points_user_campaign_points')
    # ### end Alembic commands ###
