"""Add PartnerProtocolSnapshot table

Revision ID: 811cbc8e30b4
Revises: 95d9534fe516
Create Date: 2025-08-29 17:37:33.851035

"""
import sqlmodel
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '811cbc8e30b4'
down_revision: Union[str, None] = '95d9534fe516'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('partner_protocol_snapshot',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('wallet_address', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('protocol_slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('protocol_type', sa.Enum('DEX_UNISWAPV3', 'LENDING_HYPURRFI', 'YIELD_PENDLE', name='protocoltype'), nullable=False),
    sa.Column('quantity_type', sa.Enum('LP', 'YT', 'BORROW', name='quantitytype'), nullable=False),
    sa.Column('token_address', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('block_number', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=78, scale=0), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_partner_protocol_snapshot_protocol_slug'), 'partner_protocol_snapshot', ['protocol_slug'], unique=False)
    op.create_index(op.f('ix_partner_protocol_snapshot_quantity_type'), 'partner_protocol_snapshot', ['quantity_type'], unique=False)
    op.create_index(op.f('ix_partner_protocol_snapshot_timestamp'), 'partner_protocol_snapshot', ['timestamp'], unique=False)
    op.create_index(op.f('ix_partner_protocol_snapshot_token_address'), 'partner_protocol_snapshot', ['token_address'], unique=False)
    op.create_index(op.f('ix_partner_protocol_snapshot_wallet_address'), 'partner_protocol_snapshot', ['wallet_address'], unique=False)
    op.create_index('ix_snapshot_position_time', 'partner_protocol_snapshot', ['wallet_address', 'protocol_slug', 'quantity_type', 'token_address', 'block_number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_snapshot_position_time', table_name='partner_protocol_snapshot')
    op.drop_index(op.f('ix_partner_protocol_snapshot_wallet_address'), table_name='partner_protocol_snapshot')
    op.drop_index(op.f('ix_partner_protocol_snapshot_token_address'), table_name='partner_protocol_snapshot')
    op.drop_index(op.f('ix_partner_protocol_snapshot_timestamp'), table_name='partner_protocol_snapshot')
    op.drop_index(op.f('ix_partner_protocol_snapshot_quantity_type'), table_name='partner_protocol_snapshot')
    op.drop_index(op.f('ix_partner_protocol_snapshot_protocol_slug'), table_name='partner_protocol_snapshot')
    op.drop_table('partner_protocol_snapshot')
    # ### end Alembic commands ###
