"""Set pool_address nullable in points campaign table

Revision ID: 95d9534fe516
Revises: c96d53340e8b
Create Date: 2025-08-27 09:13:04.697001

"""
import sqlmodel
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95d9534fe516'
down_revision: Union[str, None] = 'c96d53340e8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('points_campaign', 'pool_address',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('points_campaign', 'pool_address',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
