"""Add PartnerPoolUniswapV3 table

Revision ID: 97d8dfef59d8
Revises: 6736db302973
Create Date: 2025-08-20 15:17:36.262380

"""
import sqlmodel
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97d8dfef59d8'
down_revision: Union[str, None] = '6736db302973'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('partner_pool_uniswapv3',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pool_slug', sa.String(), nullable=False),
    sa.Column('token0_address', sa.String(), nullable=False),
    sa.Column('token1_address', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pool_slug'], ['partner_pool.slug'], ),
    sa.ForeignKeyConstraint(['token0_address'], ['tokens.address'], ),
    sa.ForeignKeyConstraint(['token1_address'], ['tokens.address'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_partner_pool_uniswapv3_pool_slug'), 'partner_pool_uniswapv3', ['pool_slug'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_partner_pool_uniswapv3_pool_slug'), table_name='partner_pool_uniswapv3')
    op.drop_table('partner_pool_uniswapv3')
    # ### end Alembic commands ###
