"""Add PartnerUniswapV3LP table

Revision ID: 98976219c601
Revises: b34ba70b70e3
Create Date: 2025-08-20 06:47:30.197279

"""
import sqlmodel
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98976219c601'
down_revision: Union[str, None] = 'b34ba70b70e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('partner_uniswapv3_lp',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('pool_slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('nft_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('price_lower_tick', sa.Integer(), nullable=False),
    sa.Column('price_upper_tick', sa.Integer(), nullable=False),
    sa.Column('liquidity', sa.Numeric(precision=36, scale=0), nullable=False),
    sa.Column('wallet_address', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_partner_uniswapv3_lp_pool_slug'), 'partner_uniswapv3_lp', ['pool_slug'], unique=False)
    op.create_index(op.f('ix_partner_uniswapv3_lp_nft_id'), 'partner_uniswapv3_lp', ['nft_id'], unique=False)
    op.create_index(op.f('ix_partner_uniswapv3_lp_wallet_address'), 'partner_uniswapv3_lp', ['wallet_address'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_partner_uniswapv3_lp_pool_slug'), table_name='partner_uniswapv3_lp')
    op.drop_index(op.f('ix_partner_uniswapv3_lp_nft_id'), table_name='partner_uniswapv3_lp')
    op.drop_index(op.f('ix_partner_uniswapv3_lp_wallet_address'), table_name='partner_uniswapv3_lp')

    op.drop_table('partner_uniswapv3_lp')
    # ### end Alembic commands ###
