"""Add token_address in protocol event, user position

Revision ID: a55c6b14a7cc
Revises: d9daf41cdec5
Create Date: 2025-08-23 16:23:11.370309

"""
import sqlmodel
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a55c6b14a7cc'
down_revision: Union[str, None] = 'd9daf41cdec5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('partner_protocol_event', sa.Column('token_address', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('partner_user_position', sa.Column('token_address', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.drop_index(op.f('ix_partner_user_position_protocol_type'), table_name='partner_user_position')
    op.drop_constraint(op.f('uq_user_protocol_quantity'), 'partner_user_position', type_='unique')
    op.create_unique_constraint('uq_user_protocol_quantity_token', 'partner_user_position', ['wallet_address', 'protocol_slug', 'quantity_type', 'token_address'])
    op.create_foreign_key(None, 'points_user_point_history', 'points_user_campaign_points', ['source_event_id'], ['id'])
    ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'points_user_point_history', type_='foreignkey')
    op.drop_constraint('uq_user_protocol_quantity_token', 'partner_user_position', type_='unique')
    op.create_unique_constraint(op.f('uq_user_protocol_quantity'), 'partner_user_position', ['wallet_address', 'protocol_slug', 'quantity_type'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_partner_user_position_protocol_type'), 'partner_user_position', ['protocol_type'], unique=False)
    op.drop_column('partner_user_position', 'token_address')
    op.drop_column('partner_protocol_event', 'token_address')
    # ### end Alembic commands ###
