"""Create PartnerUserPosition table

Revision ID: c49d4ee35b08
Revises: 0f2d9f9d058c
Create Date: 2025-08-23 02:33:16.206436

"""
import sqlmodel
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'c49d4ee35b08'
down_revision: Union[str, None] = '0f2d9f9d058c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

protocol_type_enum = postgresql.ENUM('DEX_UNISWAPV3', 'LENDING_HYPURRFI', 'YIELD_PENDLE', name='protocoltype')
quantity_type_enum = postgresql.ENUM('LP', 'YT', 'BORROW', name='quantitytype')


def upgrade() -> None:
    """Upgrade schema."""

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('partner_user_position',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('wallet_address', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('protocol_slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        
        # Use the predefined enum types in the column definitions
        sa.Column('protocol_type', protocol_type_enum, nullable=False),
        sa.Column('quantity_type', quantity_type_enum, nullable=False),
        
        sa.Column('quantity', sa.Numeric(precision=78, scale=0), server_default='0', nullable=False),
        sa.Column('quantity_usd', sa.Numeric(precision=36, scale=18), server_default='0', nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('wallet_address', 'protocol_slug', 'quantity_type', name='uq_user_protocol_quantity')
    )
    # The autogenerated index name was missing the new column, corrected here
    op.create_index(op.f('ix_partner_user_position_protocol_type'), 'partner_user_position', ['protocol_type'], unique=False)
    op.create_index(op.f('ix_partner_user_position_protocol_slug'), 'partner_user_position', ['protocol_slug'], unique=False)
    op.create_index(op.f('ix_partner_user_position_quantity_type'), 'partner_user_position', ['quantity_type'], unique=False)
    op.create_index(op.f('ix_partner_user_position_wallet_address'), 'partner_user_position', ['wallet_address'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_partner_user_position_wallet_address'), table_name='partner_user_position')
    op.drop_index(op.f('ix_partner_user_position_quantity_type'), table_name='partner_user_position')
    op.drop_index(op.f('ix_partner_user_position_protocol_slug'), table_name='partner_user_position')
    op.drop_index(op.f('ix_partner_user_position_protocol_type'), table_name='partner_user_position')
    op.drop_table('partner_user_position')

    # Explicitly drop the ENUM types, but only if they exist.
    protocol_type_enum.drop(op.get_bind(), checkfirst=True)
    quantity_type_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###