"""Add PartnerPool table

Revision ID: c64dda80a17a
Revises: 6db46051c90f
Create Date: 2025-08-20 05:05:26.785397

"""
import sqlmodel
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c64dda80a17a'
down_revision: Union[str, None] = '6db46051c90f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('partner_pool',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('partner_slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tags', postgresql.ARRAY(sa.String()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_partner_pool_name'), 'partner_pool', ['name'], unique=False)
    op.create_index(op.f('ix_partner_pool_partner_slug'), 'partner_pool', ['partner_slug'], unique=False)
    op.create_index(op.f('ix_partner_pool_slug'), 'partner_pool', ['slug'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_partner_pool_slug'), table_name='partner_pool')
    op.drop_index(op.f('ix_partner_pool_partner_slug'), table_name='partner_pool')
    op.drop_index(op.f('ix_partner_pool_name'), table_name='partner_pool')
    op.drop_table('partner_pool')
    # ### end Alembic commands ###
