"""Add partner_slug in PointsUserCampaignPoints table

Revision ID: c96d53340e8b
Revises: f2d251b48947
Create Date: 2025-08-27 09:00:51.783612

"""
import sqlmodel
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c96d53340e8b'
down_revision: Union[str, None] = 'f2d251b48947'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('points_user_campaign_points', sa.Column('partner_slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.create_index(op.f('ix_points_user_campaign_points_partner_slug'), 'points_user_campaign_points', ['partner_slug'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_points_user_campaign_points_partner_slug'), table_name='points_user_campaign_points')
    op.drop_column('points_user_campaign_points', 'partner_slug')
    # ### end Alembic commands ###
