"""Add PartnerUniswapV3Tick table

Revision ID: e3b89ce7fd7e
Revises: 98976219c601
Create Date: 2025-08-20 08:04:28.717333

"""
import sqlmodel
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3b89ce7fd7e'
down_revision: Union[str, None] = '98976219c601'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('partner_uniswapv3_ticks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('pool_slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tick_idx', sa.Integer(), nullable=False),
    sa.Column('block_number', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_partner_uniswapv3_ticks_pool_slug'), 'partner_uniswapv3_ticks', ['pool_slug'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_partner_uniswapv3_ticks_pool_slug'), table_name='partner_uniswapv3_ticks')
    op.drop_table('partner_uniswapv3_ticks')
    # ### end Alembic commands ###
